# Generated by Django 3.0.6 on 2020-08-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_web', '0003_auto_20200818_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('contents', models.CharField(blank=True, max_length=200)),
                ('nickName', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
