# Generated by Django 3.0.6 on 2020-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_web', '0004_auto_20200818_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoboard',
            name='kindOfStudy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
