# Generated by Django 3.0.6 on 2020-08-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_web', '0005_auto_20200827_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoboard',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
